updates to tasks.yml

diff --git a/.github/workflows/tasks.yml b/.github/workflows/tasks.yml
--- a/.github/workflows/tasks.yml
+++ b/.github/workflows/tasks.yml
@@ -44,8 +44,29 @@ on:
 
 jobs:
 
+  preflight:
+    runs-on: ubuntu-latest
+    steps:
+    - name: catch unauthorised destructive operations
+      run: |
+        if [[ "${{ inputs.Task }}" = 'db upgrade to head' ]] &&
+           [[ "${{ github.event.inputs.Destructive }}" = 'false' ]] ||
+           [[ "${{ inputs.Task }}" = 'db upgrade to next' ]] &&
+           [[ "${{ github.event.inputs.Destructive }}" = 'false' ]] ||
+           [[ "${{ inputs.Task }}" = 'db downgrade to previous' ]] &&
+           [[ "${{ github.event.inputs.Destructive }}" = 'false' ]] ; then
+             echo "::error::'${{ inputs.Task }}' needs destructive option"
+             exit 1
+        else
+             echo "::notice::Preparing '${{ inputs.Task }}' update in ${{ inputs.Environment }}"
+             echo "::notice::Targeting regions - '${{ inputs.region }}'"
+             echo "::notice::Timeout - '${{ inputs.Timeout }}'"
+             exit 0
+        fi
+
   current:
     if: inputs.Task == 'db current revision'
+    needs: preflight
     uses: hypothesis/workflows/.github/workflows/eb-task.yml@main
     with:
       App: 'h'
@@ -58,6 +79,7 @@ jobs:
 
   head:
     if: inputs.Task == 'db upgrade to head' && github.event.inputs.Destructive == 'true'
+    needs: preflight
     uses: hypothesis/workflows/.github/workflows/eb-task.yml@main
     with:
       App: ${{ github.event.repository.name }}
@@ -69,6 +91,7 @@ jobs:
 
   next:
     if: inputs.Task == 'db upgrade to next' && github.event.inputs.Destructive == 'true'
+    needs: preflight
     uses: hypothesis/workflows/.github/workflows/eb-task.yml@main
     with:
       App: ${{ github.event.repository.name }}
@@ -80,6 +103,7 @@ jobs:
 
   downgrade:
     if: inputs.Task == 'db downgrade to previous' && github.event.inputs.Destructive == 'true'
+    needs: preflight
     uses: hypothesis/workflows/.github/workflows/eb-task.yml@main
     with:
       App: ${{ github.event.repository.name }}
@@ -88,14 +112,3 @@ jobs:
       Region: ${{ inputs.Region }}
       Command: 'hypothesis migrate downgrade -1'
     secrets: inherit
-
-  unauthorised:
-    runs-on: ubuntu-latest
-    if: inputs.Task == 'db upgrade to head' && github.event.inputs.Destructive == 'false'
-      || inputs.Task == 'db upgrade to next' && github.event.inputs.Destructive == 'false'
-      || inputs.Task == 'db downgrade to previous' && github.event.inputs.Destructive == 'false'
-    steps:
-    - name: catch unauthorised destructive operation
-      run: |
-        echo "::error::'${{ inputs.Task }}' needs destructive option"
-        exit 1
